library(twitteR)
library(ROAuth)
library(httpuv)
library(SnowballC)
setup_twitter_oauth("XIX9FbPathlyo4ZkncF98NgsI", "4BaIY3gF41ZW2DT2lLEUmGW6j79x3XsohJrgzOnfZx28jINRrH")
tweets <- searchTwitter('#VIT',n=50)
head(tweets)
head(strip_retweets(tweets,strip_manual=TRUE,strip_mt=TRUE))
ram <- getUser('rameshragala')
ram$getDescription()
ram$getFollowersCount()
ram$getFavorites()
ram$getFriends(n=3)
df <- twListToDF(tweets)
head(df)
rdmTweets <- userTimeline("rdatamining", n=100)
head(rdmTweets)
n <- length(rdmTweets)
n
rdmTweets[1:3]
df <- do.call("rbind", lapply(rdmTweets, as.data.frame))
dim(df)
library(tm)
myCorpus <- Corpus(VectorSource(df$text))
myCorpus <- tm_map(myCorpus, tolower)
myCorpus <- tm_map(myCorpus, removePunctuation)
myCorpus <- tm_map(myCorpus, removeNumbers)
myStopwords <- c(stopwords('english'), "available", "via")
idx <- which(myStopwords == "r")
myStopwords <- myStopwords[-idx]
myCorpus <- tm_map(myCorpus, removeWords, myStopwords)
dictCorpus <- myCorpus
myCorpus <- tm_map(myCorpus, stemDocument)
inspect(myCorpus[1:3])
myCorpus <- tm_map(myCorpus, stemCompletion, dictionary=dictCorpus)
inspect(myCorpus[1:3])
myDtm <- TermDocumentMatrix(myCorpus, control = list(minWordLength = 1))
inspect(myDtm[266:270,31:40])

